### ISSUE TITLE
ActiveRecord::NoDatabaseError when running bundle exec rails db:setup ? (Postgis)

### ISSUE THREAD

**Issue by ksouthworth** [setup-rails/setup-rails#17]
I have my database configured in `database.yml` and I can run `rails db:setup` on my local machine, but when running through the Github Actions it's failing on the `rails db:setup` step with the following error:

```
Run bundle exec rails db:setup
  
  bundle exec rails db:setup
  shell: /usr/bin/bash -e {0}
  env:
    BUNDLE_WITHOUT: development
    PGHOST: localhost
    PGUSER: postgres
    PGPASSWORD: postgres
    RAILS_ENV: test
rails aborted!
ActiveRecord::NoDatabaseError: We could not find your database: customer_portal_test. Which can be found in the database configuration file located at config/database.yml.

To resolve this issue:

- Did you create the database for this app, or delete it? You may need to create your database.
- Has the database name changed? Check your database.yml config has the correct database name.

To create your database, run:

        bin/rails db:create
```

**Comment by andyw8** [comment]
Hi @ksouthworth, would you mind sharing your `config/database.yml`? You can take out anything sensitive.

**Comment by ksouthworth** [comment]
of course, here's my `database.yml`

```yml
default: &default
  adapter: postgis
  encoding: unicode
  port: <%= ENV.fetch("DATABASE_PORT") { 5432 } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: customer_portal_development

test:
  <<: *default
  database: customer_portal_test
```
